FROM node:24-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
# should use npm ci but now I have sub-modules conflict error so for now I will skip
COPY . .
RUN npm run build

FROM nginx:stable-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
# COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]