services:
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    env_file:
      - ./frontend/.env
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - frontend


  server:

    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/__pycache__
    depends_on:
      - db
    networks:
      - frontend
      - backend


  db:
    image: chromadb/chroma
    volumes:
    - ./db/data:/chroma
    ports:
    - "5000:8000"
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge