apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    name: app
spec:
  selector:
    matchLabels:
      run: app
  template:
    metadata:
      labels:
        run: app
    spec:
      containers:
      - name: app
        image: pee0982817150/devops-practice-frontend
        ports:
        - containerPort: 80
        env:
          - name: VITE_API_URL
            valueFrom:
              configMapKeyRef:
                name:  all-config
                key:  VITE_API_URL
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    run: app
spec:
  ports:
  - port: 80
  selector:
    run: app