# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: devops-ingress
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /$1
# spec:
#   rules:
#   - host: dev.local
#     http:
#       paths:
#       - path: /?(.*)
#         pathType: ImplementationSpecific
#         backend:
#           service:
#             name: app-service
#             port:
#               number: 80
#       - path: /api/?(.*)
#         pathType: ImplementationSpecific
#         backend:
#           service:
#             name: backend-service
#             port:
#               number: 8000
#       - path: /inference/?(.*)
#         pathType: ImplementationSpecific
#         backend:
#           service:
#             name: inference-service
#             port:
#               number: 8000

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: dev.local
    http:
      paths:
      - path: /api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: backend-service
            port:
              number: 8000
      - path: /inference(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: inference-service
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-service
            port:
              number: 80
